const HOUSEWORK_STORAGE_KEY="myHouseworkRecords";
const currentHouseworkForm=document.querySelector("#current-housework-form");
const currentHouseworkOther=document.querySelector("#current-housework-other");
const currentHouseworkNote=document.querySelector("#current-housework-note");
const manualHouseworkForm=document.querySelector("#manual-housework-form");
const manualHouseworkOther=document.querySelector("#manual-housework-other");
const manualHouseworkDatetime=document.querySelector("#manual-housework-datetime");
const manualHouseworkNote=document.querySelector("#manual-housework-note");
const editingHouseworkRecordIdInput=document.querySelector("#editing-housework-record-id");
const houseworkRecordEditingMessage=document.querySelector("#housework-record-editing-message");
const manualHouseworkSaveButton=document.querySelector("#manual-housework-save-button");
const cancelHouseworkRecordEditButton=document.querySelector("#cancel-housework-record-edit");
const houseworkStatusMessage=document.querySelector("#housework-status-message");
const houseworkRecordList=document.querySelector("#housework-record-list");
function loadHouseworkRecords(){return loadArrayFromStorage(HOUSEWORK_STORAGE_KEY);}
function saveHouseworkRecords(v){saveArrayToStorage(HOUSEWORK_STORAGE_KEY,v);}
function getSelectedHousework(name,other){const items=Array.from(document.querySelectorAll(`input[name="${name}"]:checked`)).map(x=>x.value);if(other.value.trim())items.push(other.value.trim());return items;}
function formatHouseworkDateTime(v){return formatJapaneseDateTime(v);}
function setCurrentHouseworkDateTime(){manualHouseworkDatetime.value=formatDateTimeLocalValue(new Date().toISOString());}
function showHouseworkStatus(m){houseworkStatusMessage.textContent=m;setTimeout(()=>{if(houseworkStatusMessage.textContent===m)houseworkStatusMessage.textContent="";},4000);}
function refreshHouseworkAndSync(){if(typeof refreshAllScreens==="function")refreshAllScreens();else displayHouseworkRecords();if(window.firebaseSync?.queueUpload)window.firebaseSync.queueUpload();}
function displayHouseworkRecords(){const records=loadHouseworkRecords().sort((a,b)=>new Date(b.datetime)-new Date(a.datetime));houseworkRecordList.innerHTML=records.length?records.map(r=>`<article class="housework-record-card"><div class="housework-record-header"><div><h3>家事</h3><p class="housework-datetime">${formatHouseworkDateTime(r.datetime)}</p></div><div class="record-action-buttons"><button type="button" class="edit-button housework-edit-button" data-housework-id="${r.id}">編集</button><button type="button" class="delete-button housework-delete-button" data-housework-id="${r.id}">削除</button></div></div><p class="housework-items">${(r.items||[]).map(escapeHtml).join("、")}</p><p class="record-note"><strong>メモ：</strong>${escapeHtml(r.note||"なし")}</p></article>`).join(""):'<p class="empty-message">まだ家事記録はありません。</p>';}
function cancelHouseworkRecordEditing(){editingHouseworkRecordIdInput.value="";manualHouseworkForm.reset();setCurrentHouseworkDateTime();manualHouseworkSaveButton.textContent="家事記録を保存";houseworkRecordEditingMessage.classList.add("hidden-button");cancelHouseworkRecordEditButton.classList.add("hidden-button");}
function startHouseworkRecordEditing(id){const r=loadHouseworkRecords().find(x=>String(x.id)===String(id));if(!r)return alert("編集する家事記録が見つかりません。");editingHouseworkRecordIdInput.value=r.id;const boxes=Array.from(document.querySelectorAll('input[name="manual-housework"]'));const fixed=boxes.map(x=>x.value);boxes.forEach(x=>x.checked=(r.items||[]).includes(x.value));manualHouseworkOther.value=(r.items||[]).filter(x=>!fixed.includes(x)).join("、");manualHouseworkDatetime.value=formatDateTimeLocalValue(r.datetime);manualHouseworkNote.value=r.note||"";manualHouseworkSaveButton.textContent="変更を保存";houseworkRecordEditingMessage.classList.remove("hidden-button");cancelHouseworkRecordEditButton.classList.remove("hidden-button");manualHouseworkForm.scrollIntoView({behavior:"smooth",block:"start"});}
currentHouseworkForm.addEventListener("submit",e=>{e.preventDefault();const items=getSelectedHousework("current-housework",currentHouseworkOther);if(!items.length)return alert("行った家事を1つ以上選択してください。");const records=loadHouseworkRecords();records.push({id:createRecordId(),items,datetime:new Date().toISOString(),note:currentHouseworkNote.value.trim()});saveHouseworkRecords(records);currentHouseworkForm.reset();refreshHouseworkAndSync();showHouseworkStatus("現在時刻で家事を記録しました。");});
manualHouseworkForm.addEventListener("submit",e=>{e.preventDefault();const items=getSelectedHousework("manual-housework",manualHouseworkOther);if(!items.length)return alert("行った家事を1つ以上選択してください。");if(!manualHouseworkDatetime.value)return alert("実施日時を入力してください。");const records=loadHouseworkRecords();const id=editingHouseworkRecordIdInput.value;if(id){const r=records.find(x=>String(x.id)===String(id));if(!r)return alert("編集する家事記録が見つかりません。");r.items=items;r.datetime=new Date(manualHouseworkDatetime.value).toISOString();r.note=manualHouseworkNote.value.trim();}else records.push({id:createRecordId(),items,datetime:new Date(manualHouseworkDatetime.value).toISOString(),note:manualHouseworkNote.value.trim()});const edited=Boolean(id);saveHouseworkRecords(records);cancelHouseworkRecordEditing();refreshHouseworkAndSync();showHouseworkStatus(edited?"家事記録を変更しました。":"家事記録を保存しました。");});
houseworkRecordList.addEventListener("click",e=>{const edit=e.target.closest(".housework-edit-button");if(edit)return startHouseworkRecordEditing(edit.dataset.houseworkId);const del=e.target.closest(".housework-delete-button");if(!del||!confirm("この家事記録を削除しますか？"))return;saveHouseworkRecords(loadHouseworkRecords().filter(r=>String(r.id)!==String(del.dataset.houseworkId)));refreshHouseworkAndSync();});
cancelHouseworkRecordEditButton.addEventListener("click",cancelHouseworkRecordEditing);
setCurrentHouseworkDateTime();displayHouseworkRecords();
