const MEDICINE_LIST_STORAGE_KEY = "myRegisteredMedicines";
const MEDICINE_RECORD_STORAGE_KEY = "myMedicineRecords";
const medicineQuickList=document.querySelector("#medicine-quick-list");
const medicineRegistrationForm=document.querySelector("#medicine-registration-form");
const editingMedicineIdInput=document.querySelector("#editing-medicine-id");
const medicineFormTitle=document.querySelector("#medicine-form-title");
const medicineNameInput=document.querySelector("#medicine-name");
const medicineDefaultDoseInput=document.querySelector("#medicine-default-dose");
const medicineDefaultNoteInput=document.querySelector("#medicine-default-note");
const medicineRegistrationSubmit=document.querySelector("#medicine-registration-submit");
const cancelMedicineEditButton=document.querySelector("#cancel-medicine-edit");
const registeredMedicineList=document.querySelector("#registered-medicine-list");
const currentMedicineForm=document.querySelector("#current-medicine-form");
const currentMedicineSelect=document.querySelector("#current-medicine-select");
const currentMedicineDoseInput=document.querySelector("#current-medicine-dose");
const currentMedicineNoteInput=document.querySelector("#current-medicine-note");
const manualMedicineForm=document.querySelector("#manual-medicine-form");
const manualMedicineSelect=document.querySelector("#manual-medicine-select");
const manualMedicineDatetimeInput=document.querySelector("#manual-medicine-datetime");
const manualMedicineDoseInput=document.querySelector("#manual-medicine-dose");
const manualMedicineNoteInput=document.querySelector("#manual-medicine-note");
const editingMedicineRecordIdInput=document.querySelector("#editing-medicine-record-id");
const medicineRecordEditingMessage=document.querySelector("#medicine-record-editing-message");
const manualMedicineSaveButton=document.querySelector("#manual-medicine-save-button");
const cancelMedicineRecordEditButton=document.querySelector("#cancel-medicine-record-edit");
const medicineRecordList=document.querySelector("#medicine-record-list");
const medicineStatusMessage=document.querySelector("#medicine-status-message");

function loadRegisteredMedicines(){return loadArrayFromStorage(MEDICINE_LIST_STORAGE_KEY).map(m=>({...m,defaultNote:m.defaultNote||""}));}
function saveRegisteredMedicines(v){saveArrayToStorage(MEDICINE_LIST_STORAGE_KEY,v);}
function loadMedicineRecords(){return loadArrayFromStorage(MEDICINE_RECORD_STORAGE_KEY);}
function saveMedicineRecords(v){saveArrayToStorage(MEDICINE_RECORD_STORAGE_KEY,v);}
function findMedicineById(id){return loadRegisteredMedicines().find(m=>String(m.id)===String(id));}
function showMedicineStatus(message){medicineStatusMessage.textContent=message;setTimeout(()=>{if(medicineStatusMessage.textContent===message)medicineStatusMessage.textContent="";},4000);}
function setCurrentMedicineDateTime(){manualMedicineDatetimeInput.value=formatDateTimeLocalValue(new Date().toISOString());}
function refreshMedicineAndSync(){if(typeof refreshAllScreens==="function")refreshAllScreens();else{displayRegisteredMedicines();displayMedicineRecords();}if(window.firebaseSync?.queueUpload)window.firebaseSync.queueUpload();}
function updateMedicineSelects(){const options=loadRegisteredMedicines().map(m=>`<option value="${m.id}">${escapeHtml(m.name)}</option>`).join("");currentMedicineSelect.innerHTML='<option value="">薬を選択してください</option>'+options;manualMedicineSelect.innerHTML='<option value="">薬を選択してください</option>'+options;}
function displayMedicineQuickButtons(){const meds=loadRegisteredMedicines();medicineQuickList.innerHTML=meds.length?meds.map(m=>`<button type="button" class="quick-record-button medicine-quick-button" data-medicine-id="${m.id}"><strong>${escapeHtml(m.name)}</strong><span>${escapeHtml(m.defaultDose||"服用量未設定")}</span></button>`).join(""):'<p class="empty-message">まだ薬は登録されていません。</p>';}
function displayRegisteredMedicines(){const meds=loadRegisteredMedicines();registeredMedicineList.innerHTML=meds.length?meds.map(m=>`<div class="registered-medicine-card"><div class="registered-medicine-information"><p class="registered-medicine-name">${escapeHtml(m.name)}</p><p class="registered-medicine-dose">通常量：${escapeHtml(m.defaultDose||"未設定")}<br>メモ：${escapeHtml(m.defaultNote||"なし")}</p></div><div class="record-action-buttons"><button type="button" class="edit-button registered-medicine-edit-button" data-medicine-id="${m.id}">編集</button><button type="button" class="delete-button registered-medicine-delete-button" data-medicine-id="${m.id}">削除</button></div></div>`).join(""):'<p class="empty-message">まだ薬は登録されていません。</p>';updateMedicineSelects();displayMedicineQuickButtons();}
function displayMedicineRecords(){const records=loadMedicineRecords().sort((a,b)=>new Date(b.datetime)-new Date(a.datetime));medicineRecordList.innerHTML=records.length?records.map(r=>`<article class="medicine-record-card"><div class="medicine-record-header"><div><h3>${escapeHtml(r.medicineName)}</h3><p class="medicine-record-datetime">${formatJapaneseDateTime(r.datetime)}</p></div><div class="record-action-buttons"><button type="button" class="edit-button medicine-record-edit-button" data-medicine-record-id="${r.id}">編集</button><button type="button" class="delete-button medicine-record-delete-button" data-medicine-record-id="${r.id}">削除</button></div></div><div class="medicine-record-details"><p><strong>服用量：</strong>${escapeHtml(r.dose||"未入力")}</p><p><strong>メモ：</strong>${escapeHtml(r.note||"なし")}</p></div></article>`).join(""):'<p class="empty-message">まだ服用記録はありません。</p>';}
function cancelMedicineEditing(){editingMedicineIdInput.value="";medicineRegistrationForm.reset();medicineFormTitle.textContent="薬を登録";medicineRegistrationSubmit.textContent="薬を登録";cancelMedicineEditButton.classList.add("hidden-button");}
function startMedicineEditing(id){const m=findMedicineById(id);if(!m)return;editingMedicineIdInput.value=m.id;medicineNameInput.value=m.name;medicineDefaultDoseInput.value=m.defaultDose||"";medicineDefaultNoteInput.value=m.defaultNote||"";medicineFormTitle.textContent="薬を編集";medicineRegistrationSubmit.textContent="変更を保存";cancelMedicineEditButton.classList.remove("hidden-button");medicineRegistrationForm.scrollIntoView({behavior:"smooth",block:"start"});}
function addMedicineRecord(medicine,dose,note,datetime){const records=loadMedicineRecords();records.push({id:createRecordId(),medicineId:medicine.id,medicineName:medicine.name,dose,note,datetime});saveMedicineRecords(records);refreshMedicineAndSync();}
function cancelMedicineRecordEditing(){editingMedicineRecordIdInput.value="";manualMedicineForm.reset();setCurrentMedicineDateTime();manualMedicineSaveButton.textContent="服用記録を保存";medicineRecordEditingMessage.classList.add("hidden-button");cancelMedicineRecordEditButton.classList.add("hidden-button");}
function startMedicineRecordEditing(id){const r=loadMedicineRecords().find(x=>String(x.id)===String(id));if(!r)return alert("編集する服用記録が見つかりません。");editingMedicineRecordIdInput.value=r.id;let option=Array.from(manualMedicineSelect.options).find(o=>o.textContent.trim()===r.medicineName);manualMedicineSelect.value=option?option.value:"";manualMedicineDatetimeInput.value=formatDateTimeLocalValue(r.datetime);manualMedicineDoseInput.value=r.dose||"";manualMedicineNoteInput.value=r.note||"";manualMedicineSaveButton.textContent="変更を保存";medicineRecordEditingMessage.classList.remove("hidden-button");cancelMedicineRecordEditButton.classList.remove("hidden-button");manualMedicineForm.scrollIntoView({behavior:"smooth",block:"start"});}

medicineRegistrationForm.addEventListener("submit",e=>{e.preventDefault();const name=medicineNameInput.value.trim();if(!name)return alert("薬の名前を入力してください。");const meds=loadRegisteredMedicines();const id=editingMedicineIdInput.value;if(meds.some(m=>String(m.id)!==String(id)&&m.name.toLowerCase()===name.toLowerCase()))return alert("同じ名前の薬が登録されています。");if(id){const m=meds.find(x=>String(x.id)===String(id));if(!m)return;m.name=name;m.defaultDose=medicineDefaultDoseInput.value.trim();m.defaultNote=medicineDefaultNoteInput.value.trim();}else meds.push({id:createRecordId(),name,defaultDose:medicineDefaultDoseInput.value.trim(),defaultNote:medicineDefaultNoteInput.value.trim()});saveRegisteredMedicines(meds);cancelMedicineEditing();refreshMedicineAndSync();});
cancelMedicineEditButton.addEventListener("click",cancelMedicineEditing);
medicineQuickList.addEventListener("click",e=>{const b=e.target.closest(".medicine-quick-button");if(!b)return;const m=findMedicineById(b.dataset.medicineId);if(m)addMedicineRecord(m,m.defaultDose||"",m.defaultNote||"",new Date().toISOString());});
currentMedicineForm.addEventListener("submit",e=>{e.preventDefault();const m=findMedicineById(currentMedicineSelect.value);if(!m)return alert("薬を選択してください。");addMedicineRecord(m,currentMedicineDoseInput.value.trim()||m.defaultDose,currentMedicineNoteInput.value.trim(),new Date().toISOString());currentMedicineForm.reset();});
manualMedicineForm.addEventListener("submit",e=>{e.preventDefault();if(!manualMedicineDatetimeInput.value)return alert("服用日時を入力してください。");const editingId=editingMedicineRecordIdInput.value;const records=loadMedicineRecords();const selected=findMedicineById(manualMedicineSelect.value);if(editingId){const r=records.find(x=>String(x.id)===String(editingId));if(!r)return alert("編集する服用記録が見つかりません。");r.datetime=new Date(manualMedicineDatetimeInput.value).toISOString();r.dose=manualMedicineDoseInput.value.trim();r.note=manualMedicineNoteInput.value.trim();if(selected){r.medicineId=selected.id;r.medicineName=selected.name;}}else{if(!selected)return alert("薬を選択してください。");records.push({id:createRecordId(),medicineId:selected.id,medicineName:selected.name,dose:manualMedicineDoseInput.value.trim()||selected.defaultDose,note:manualMedicineNoteInput.value.trim(),datetime:new Date(manualMedicineDatetimeInput.value).toISOString()});}const edited=Boolean(editingId);saveMedicineRecords(records);cancelMedicineRecordEditing();refreshMedicineAndSync();showMedicineStatus(edited?"服用記録を変更しました。":"服用記録を保存しました。");});
currentMedicineSelect.addEventListener("change",()=>{const m=findMedicineById(currentMedicineSelect.value);currentMedicineDoseInput.value=m?.defaultDose||"";currentMedicineNoteInput.value=m?.defaultNote||"";});
manualMedicineSelect.addEventListener("change",()=>{if(editingMedicineRecordIdInput.value)return;const m=findMedicineById(manualMedicineSelect.value);manualMedicineDoseInput.value=m?.defaultDose||"";manualMedicineNoteInput.value=m?.defaultNote||"";});
registeredMedicineList.addEventListener("click",e=>{const edit=e.target.closest(".registered-medicine-edit-button");if(edit)return startMedicineEditing(edit.dataset.medicineId);const del=e.target.closest(".registered-medicine-delete-button");if(!del||!confirm("この薬を登録一覧から削除しますか？\n過去の服用記録は残ります。"))return;saveRegisteredMedicines(loadRegisteredMedicines().filter(m=>String(m.id)!==String(del.dataset.medicineId)));cancelMedicineEditing();refreshMedicineAndSync();});
medicineRecordList.addEventListener("click",e=>{const edit=e.target.closest(".medicine-record-edit-button");if(edit)return startMedicineRecordEditing(edit.dataset.medicineRecordId);const del=e.target.closest(".medicine-record-delete-button");if(!del||!confirm("この服用記録を削除しますか？"))return;saveMedicineRecords(loadMedicineRecords().filter(r=>String(r.id)!==String(del.dataset.medicineRecordId)));refreshMedicineAndSync();});
cancelMedicineRecordEditButton.addEventListener("click",cancelMedicineRecordEditing);
setCurrentMedicineDateTime();displayRegisteredMedicines();displayMedicineRecords();
